# Generated by Django 4.2.5 on 2025-01-28 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kisan",
            name="date_added",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="date_added",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="property",
            name="date_added",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lead",
            name="date_added",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
