# Generated by Django 5.1.1 on 2024-10-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_block_project_plot_block_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="blocks",
            field=models.ManyToManyField(
                related_name="blocks_in_project", to="leads.block"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_projects",
                to="leads.project",
            ),
        ),
    ]
