# Generated by Django 4.2.5 on 2025-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_balancetransactionlog_delete_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "carryover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("added_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
