# Generated by Django 4.2.5 on 2025-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_kisan_date_added_project_date_added_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promoter",
            name="id_card_number",
        ),
        migrations.RemoveField(
            model_name="promoter",
            name="joining_percentage",
        ),
        migrations.RemoveField(
            model_name="promoter",
            name="pan_no",
        ),
        migrations.AddField(
            model_name="promoter",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="promoter",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promoter",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promoter",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promoter",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("On Leave", "On Leave"),
                    ("Resigned", "Resigned"),
                    ("Inactive", "Inactive"),
                ],
                default="Active",
                help_text="Current employment status of the promoter.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="promoter",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promoter",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
