# Generated by Django 4.2.5 on 2025-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_remove_promoter_id_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=True),
        ),
    ]
