# Generated by Django 4.2.5 on 2025-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancetransactionlog",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
