# Generated by Django 5.1.1 on 2024-10-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_project_blocks_alter_block_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="block",
        ),
        migrations.RemoveField(
            model_name="project",
            name="blocks",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="plot_number",
        ),
        migrations.AddField(
            model_name="plot",
            name="booking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plot",
            name="plot_no",
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="plot",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.project",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Hold", "Hold"),
                    ("Sold Out", "Sold Out"),
                ],
                default="Available",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="block_code",
            field=models.CharField(default="NA", max_length=10),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Block",
        ),
    ]
