# Generated by Django 5.1.1 on 2024-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_remove_plot_block_remove_project_blocks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmiPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tenure_months", models.IntegerField()),
                (
                    "minimum_downpayment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
