# Generated by Django 4.2.5 on 2025-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_alter_user_is_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="promoter",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
