# Generated by Django 4.2.5 on 2025-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_promoter_last_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="promoter",
            name="next_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
