# Generated by Django 3.1.4 on 2024-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=False),
        ),
    ]
