# Generated by Django 5.1.1 on 2024-10-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_daybook"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promoter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("mobile_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("pan_no", models.CharField(max_length=15)),
                ("id_card_number", models.CharField(max_length=20)),
                (
                    "joining_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
