# Generated by Django 4.2.5 on 2025-01-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_promoter_next_payment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promoter",
            name="email",
        ),
    ]
