# Generated by Django 5.1.2 on 2024-10-14 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_daybook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='project_name',
        ),
        migrations.CreateModel(
            name='Project_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
