# Generated by Django 5.1.2 on 2024-10-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_promoter'),
        ('leads', '0008_alter_property_price'),
    ]

    operations = [
    ]
