# Generated by Django 5.1.1 on 2024-10-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_merge_0007_promoter_0008_alter_property_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("father_husband_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dob", models.DateField()),
                ("mobile_no", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("bank_name", models.CharField(max_length=100)),
                ("account_no", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("nominee_name", models.CharField(max_length=100)),
                ("corner_plot_10", models.BooleanField(default=False)),
                ("corner_plot_5", models.BooleanField(default=False)),
                ("full_pay_discount", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=100)),
                ("associate_detail", models.BooleanField(default=False)),
                ("basic_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("custom_payment", "Custom Payment"),
                            ("installment", "Installment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "booking_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "mode_of_payment",
                    models.CharField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("rtgs_neft", "RTGS/NEFT"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.project"
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.promoter",
                    ),
                ),
            ],
        ),
    ]
