# Generated by Django 5.1.1 on 2024-10-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_plotbooking_custom_gender_alter_plotbooking_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotbooking",
            name="project",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="plotbooking",
            name="promoter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
