# Generated by Django 5.1.1 on 2024-10-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_alter_property_id_alter_property_title"),
        ("leads", "0014_alter_plotbooking_gender"),
    ]

    operations = []
