# Generated by Django 5.1.1 on 2024-10-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0015_merge_20241015_1232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotbooking",
            name="project",
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="project_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property",
                to="leads.property",
            ),
        ),
        migrations.DeleteModel(
            name="Plot",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
