# Generated by Django 5.1.1 on 2024-10-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0016_remove_plotbooking_project_plotbooking_project_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotbooking",
            name="project_name",
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="leads.property",
            ),
        ),
        migrations.DeleteModel(
            name="Project_Name",
        ),
    ]
