# Generated by Django 5.1.1 on 2024-10-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0018_plotbooking_emi_amount_plotbooking_emi_tenure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plotbooking",
            old_name="basic_price",
            new_name="Plot_price",
        ),
    ]
