# Generated by Django 5.1.2 on 2024-10-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
