# Generated by Django 5.1.1 on 2024-10-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0020_emipayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emipayment",
            options={"ordering": ["due_date"]},
        ),
    ]
