# Generated by Django 5.1.1 on 2024-10-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0021_alter_emipayment_options"),
        ("leads", "0024_alter_property_project_name"),
    ]

    operations = []
