# Generated by Django 5.1.1 on 2024-10-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0026_alter_plotbooking_emi_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="commission_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="agent",
            name="parent_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_agents",
                to="leads.agent",
            ),
        ),
    ]
