# Generated by Django 5.1.2 on 2024-10-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_merge_20241017_1025'),
        ('leads', '0026_alter_plotbooking_emi_amount'),
    ]

    operations = [
    ]
