# Generated by Django 5.1.1 on 2024-10-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0027_agent_commission_percentage_agent_parent_agent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="commission_percentage",
            new_name="total_commission_shared",
        ),
        migrations.AlterField(
            model_name="agent",
            name="parent_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_agents",
                to="leads.agent",
            ),
        ),
    ]
