# Generated by Django 5.1.2 on 2024-10-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_merge_20241017_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=222)),
                ('interest', models.IntegerField()),
            ],
        ),
    ]
