# Generated by Django 5.1.1 on 2024-10-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leads",
            "0028_rename_commission_percentage_agent_total_commission_shared_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="total_commission_shared",
            new_name="commission_percentage",
        ),
        migrations.AddField(
            model_name="agent",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_profit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
