# Generated by Django 5.1.1 on 2024-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0030_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="area",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
