# Generated by Django 5.1.1 on 2024-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0031_alter_area_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plottype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typeofplot", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="breadth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="totalprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
