# Generated by Django 5.1.1 on 2024-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0032_plottype_property_breadth_property_length_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Typeplot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
            ],
        ),
    ]
