# Generated by Django 5.1.1 on 2024-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0033_typeplot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeplot",
            name="type",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
