# Generated by Django 5.1.1 on 2024-10-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0034_alter_typeplot_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Plottype",
        ),
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
