# Generated by Django 5.1.1 on 2024-10-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0035_delete_plottype_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
