# Generated by Django 5.1.1 on 2024-10-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0037_alter_daybook_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plotbooking",
            old_name="promoter",
            new_name="Agent",
        ),
    ]
