# Generated by Django 5.1.1 on 2024-10-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0038_rename_promoter_plotbooking_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotbooking",
            name="Agent",
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plot_bookings",
                to="leads.promoter",
            ),
        ),
    ]
