# Generated by Django 5.1.1 on 2024-10-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0039_remove_plotbooking_agent_plotbooking_agent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plotbooking",
            old_name="agent",
            new_name="Agent",
        ),
    ]
