# Generated by Django 5.1.1 on 2024-10-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0025_merge_20241017_1025"),
        ("leads", "0040_rename_agent_plotbooking_agent"),
    ]

    operations = []
