# Generated by Django 5.1.1 on 2024-10-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0041_merge_20241020_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
