# Generated by Django 5.1.1 on 2024-10-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0043_property_related_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
