# Generated by Django 5.1.2 on 2024-10-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_level'),
        ('leads', '0044_property_is_sold'),
    ]

    operations = [
    ]
