# Generated by Django 5.1.1 on 2024-10-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0046_alter_agent_organisation_alter_agent_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotbooking",
            name="Agent",
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.property",
            ),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plot_bookings",
                to="leads.agent",
            ),
        ),
    ]
