# Generated by Django 5.1.1 on 2024-10-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0048_remove_plotbooking_agent_remove_plotbooking_property_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotbooking",
            name="Agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plot_bookings",
                to="leads.agent",
            ),
        ),
    ]
