# Generated by Django 5.1.1 on 2024-10-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0049_alter_plotbooking_agent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plotbooking",
            old_name="Agent",
            new_name="agent",
        ),
    ]
