# Generated by Django 5.1.1 on 2024-10-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0050_rename_agent_plotbooking_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kisan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("contact_number", models.IntegerField()),
                ("address", models.TextField(max_length=50)),
                ("khasra_number", models.IntegerField(unique=True)),
                (
                    "area_in_beegha",
                    models.DecimalField(decimal_places=3, max_digits=20),
                ),
                ("land_costing", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "development_costing",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("kisan_payment", models.DecimalField(decimal_places=3, max_digits=10)),
                ("land_address", models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="plotbooking",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="project",
                to="leads.property",
            ),
        ),
    ]
