# Generated by Django 5.1.1 on 2024-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0052_kisan_basic_sales_price_kisan_payment_to_kisan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="contact_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
