# Generated by Django 5.1.1 on 2024-10-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0055_alter_kisan_kisan_payment_alter_kisan_land_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("postponed", "Postponed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
