# Generated by Django 5.1.1 on 2024-10-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0058_agent_total_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.userprofile",
            ),
        ),
    ]
