# Generated by Django 5.1.1 on 2024-10-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0061_alter_agent_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="leads.userprofile"
            ),
        ),
    ]
