# Generated by Django 5.1.1 on 2024-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0062_alter_agent_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="commission_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
