# Generated by Django 5.1.1 on 2024-10-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0064_balance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Balance",
        ),
    ]
