# Generated by Django 5.1.1 on 2024-10-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0065_delete_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
