# Generated by Django 5.1.1 on 2024-10-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0066_alter_lead_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
