# Generated by Django 4.2.5 on 2024-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0067_alter_lead_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
