# Generated by Django 4.2.5 on 2024-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0068_salary_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="commission_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
