# Generated by Django 4.2.5 on 2024-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0069_alter_agent_commission_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="kisan",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
