# Generated by Django 4.2.5 on 2024-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0071_salary_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="commission_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
