# Generated by Django 4.2.5 on 2024-11-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0072_alter_agent_commission_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="kisan",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="kisans",
            field=models.ManyToManyField(related_name="projects", to="leads.kisan"),
        ),
    ]
