# Generated by Django 4.2.5 on 2024-11-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0073_kisan_is_assigned_project_kisans"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lands",
            field=models.ManyToManyField(
                related_name="projects_lands", to="leads.kisan"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="kisans",
            field=models.ManyToManyField(
                related_name="projects_kisan", to="leads.kisan"
            ),
        ),
    ]
