# Generated by Django 4.2.5 on 2024-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0074_project_lands_alter_project_kisans"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="development_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
