# Generated by Django 4.2.5 on 2024-11-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0076_project_total_development_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="development_cost",
        ),
        migrations.RemoveField(
            model_name="property",
            name="land_area",
        ),
        migrations.RemoveField(
            model_name="property",
            name="land_cost",
        ),
        migrations.AddField(
            model_name="property",
            name="kisan_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="leads.kisan",
            ),
        ),
    ]
