# Generated by Django 4.2.5 on 2024-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0079_property_is_in_emi"),
    ]

    operations = [
        migrations.AddField(
            model_name="kisan",
            name="land_type",
            field=models.CharField(
                choices=[("plot", "Plot"), ("rowhouse", "Rowhouse"), ("flat", "Flat")],
                default=False,
                max_length=50,
            ),
        ),
    ]
