# Generated by Django 4.2.5 on 2024-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0081_alter_kisan_land_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kisan",
            name="land_type",
            field=models.CharField(
                choices=[("plot", "Plot"), ("rowhouse", "Rowhouse"), ("flat", "Flat")],
                default=False,
                max_length=50,
            ),
        ),
    ]
