# Generated by Django 4.2.5 on 2024-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0082_alter_kisan_land_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="kisan",
            name="usable_land_total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
