# Generated by Django 4.2.5 on 2024-11-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0083_kisan_usable_land_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_emi", "In EMI"),
                    ("sold", "Sold"),
                ],
                default="in_emi",
                max_length=10,
            ),
        ),
    ]
