# Generated by Django 4.2.5 on 2024-11-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0084_property_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="status",
        ),
    ]
