# Generated by Django 5.1.2 on 2024-11-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0084_project_type_alter_kisan_kisan_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_land_cost',
            new_name='total_land_available_fr_plotting',
        ),
    ]
