# Generated by Django 4.2.5 on 2024-11-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0085_remove_property_status"),
        (
            "leads",
            "0085_rename_total_land_cost_project_total_land_available_fr_plotting",
        ),
    ]

    operations = []
