# Generated by Django 4.2.5 on 2024-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0086_merge_20241104_1949"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
