# Generated by Django 4.2.5 on 2024-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0087_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="carryover_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
