# Generated by Django 4.2.5 on 2024-11-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0088_balance_carryover_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kisan",
            name="development_costing",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=12, null=True
            ),
        ),
    ]
