# Generated by Django 4.2.5 on 2024-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0089_alter_kisan_development_costing"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dev_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
