# Generated by Django 4.2.5 on 2024-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0091_property_plot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotbooking",
            name="Plot_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Corner", "Corner"),
                    ("Special", "Special"),
                ],
                default="Normal",
                max_length=50,
            ),
        ),
    ]
