# Generated by Django 4.2.5 on 2024-11-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0093_alter_agent_organisation_alter_agent_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="parent_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_agents",
                to="leads.agent",
            ),
        ),
    ]
