# Generated by Django 4.2.5 on 2024-11-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0095_alter_agent_organisation_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kisan",
            name="land_type",
        ),
    ]
