# Generated by Django 4.2.5 on 2024-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0096_remove_kisan_land_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_organisor",
            field=models.BooleanField(default=False),
        ),
    ]
