# Generated by Django 4.2.5 on 2024-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0099_alter_category_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="daybook",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
