# Generated by Django 4.2.5 on 2024-11-10 14:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0100_daybook_current_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=255)),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gst_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("other_charges", models.DecimalField(decimal_places=2, max_digits=10)),
                ("plot_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_details", models.TextField()),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_date", models.DateField(auto_now_add=True)),
                ("plot_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.receipt",
            ),
        ),
    ]
