# Generated by Django 4.2.5 on 2024-11-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0102_remove_plotbooking_receipt_delete_billing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotbooking",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
