# Generated by Django 4.2.5 on 2024-11-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0104_customer_invoice_product_invoiceitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
