# Generated by Django 4.2.5 on 2024-11-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0106_bill_product_billitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billitem",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="billitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.DeleteModel(
            name="BillItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
