# Generated by Django 4.2.5 on 2024-11-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0109_customer_item_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="items",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
