# Generated by Django 4.2.5 on 2024-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0111_bill_product_billitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Qty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
