# Generated by Django 4.2.5 on 2024-11-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0113_plotbooking_total_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="tax_percentage",
        ),
    ]
