# Generated by Django 4.2.5 on 2024-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0115_plotbooking_total_paidbycust"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="buyer_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
