# Generated by Django 5.1.2 on 2024-11-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0116_bill_buyer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotbooking',
            name='payment_type',
            field=models.CharField(choices=[('custom', 'Custom Payment'), ('installment', 'Installments'), ('full', 'Full Payment')], max_length=50),
        ),
    ]
