# Generated by Django 4.2.5 on 2025-01-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0118_alter_bill_buyer_number_alter_bill_buyer_pan_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="buyer_state",
            field=models.CharField(max_length=100),
        ),
    ]
