# Generated by Django 4.2.5 on 2025-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0119_alter_bill_buyer_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="buyer_number",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
